### ISSUE TITLE
关于详细资料

### ISSUE THREAD

**Issue by yingyulou** [LiuYinCarl/zos#1]
作者你好，请问这个项目有详细的资料或博客吗？我想进一步学习研究。

**Comment by LiuYinCarl** [comment]
晚上发你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yingyulou ***@***.***&gt;
发送时间: 2023年12月29日 16:25
收件人: LiuYinCarl/zos ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LiuYinCarl/zos] 关于详细资料 (Issue #1)





 
作者你好，请问这个项目有详细的资料或博客吗？我想进一步学习研究。

**Comment by LiuYinCarl** [comment]
https://pdos.csail.mit.edu/6.828/2018/xv6/book-rev11.pdf
http://staff.ustc.edu.cn/~chizhang/OS/Labs/MIT-XV6-%D6%D0%CE%C4%B7%AD%D2%EB%B0%E6.pdf


看这两个吧，不用看我的代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yingyulou ***@***.***&gt;
发送时间: 2023年12月29日 16:25
收件人: LiuYinCarl/zos ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LiuYinCarl/zos] 关于详细资料 (Issue #1)





 
作者你好，请问这个项目有详细的资料或博客吗？我想进一步学习研究。

**Comment by yingyulou** [comment]
xv6我略有研究，你的这份代码是从xv6改编/简化的吗？

**Comment by yingyulou** [comment]
PS，能留个联系方式吗？我们一起交流学习。

**Comment by LiuYinCarl** [comment]
微信
carl2024321

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yingyulou ***@***.***&gt;
发送时间: 2023年12月29日 18:00
收件人: LiuYinCarl/zos ***@***.***&gt;
抄送: Kenshin ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [LiuYinCarl/zos] 关于详细资料 (Issue #1)





 
PS，能留个联系方式吗？我们一起交流学习。

**Comment by LiuYinCarl** [comment]
我对操作系统也只是看书了解，理解不多。
